### ISSUE TITLE
Link to docker-compose.yml not in documentation

### ISSUE THREAD

**Issue by reconstructions** [shakacode/react_on_rails#1014]
When starting docker using `docker-compose build lint` per the instructions in [CONTRIBUTING.md](https://github.com/shakacode/react_on_rails/blob/master/CONTRIBUTING.md#linting), a docker-compose.yml is required, but [hasn't been checked into git for awhile](https://github.com/shakacode/react_on_rails/blame/cdb246bb7934283fbe5a99c122d5f801a10e67c0/docker-compose.yml), so an error is thrown.  I don't see any links to this config or instructions about this elsewhere in the documentation.

**Comment by justin808** [comment]
We removed docker-compose.yml here:
https://github.com/shakacode/react_on_rails/pull/497/files

This is what it contained. A PR to update the docs would be appreciated, @reconstructions. 

```yml
lint:
  image: dylangrafmyre/docker-lint
  working_dir: /app/
  volumes:
    - '.:/app/'
tests:
  build: .
  dockerfile: Dockerfile_tests
  working_dir: /app/
  volumes:
    - '.:/app/'
```
