### ISSUE TITLE
Prerender:true error

### ISSUE THREAD

**Issue by nathan-kuo** [shakacode/react_on_rails#1242]
Hi there, thanks for the great tutorial.  As I turned **prerender: true** . 

I got this error..  I searched in issues and someone had a similar error but in different context.  Could you help me out?  thanks!

`
ERROR in SERVER PRERENDERING
Encountered error: "uninitialized constant #<Class:0x00007fa4ec57e638>::ExecJS"
when prerendering HelloWorld with props: {"name":"Stranger"}

code:

        (function() {
          var railsContext = {"railsEnv":"development","inMailer":false,"i18nLocale":"en","i18nDefaultLocale":"en","rorVersion":"11.2.1","rorPro":false,"href":"http://localhost:3000/hello_world","location":"/hello_world","scheme":"http","host":"localhost","port":3000,"pathname":"/hello_world","search":null,"httpAcceptLanguage":"en-US,en;q=0.9","serverSide":true};
              ReactOnRails.clearHydratedStores();

          var props = {"name":"Stranger"};
          return ReactOnRails.serverRenderReactComponent({
            name: 'HelloWorld',
            domNodeId: 'HelloWorld-react-component-48dffa88-d404-4a79-9368-09cea348084d',
            props: props,
            trace: true,
            railsContext: railsContext
          });
        })()

`

**Comment by fabriziobertoglio1987** [comment]
from the [configuration docs](https://github.com/shakacode/react_on_rails/blob/master/docs/basics/configuration.md)

```ruby
  # The default server rendering is ExecJS, probably using the mini_racer gem
```

as it saying `"uninitialized constant #Class:0x00007fa4ec57e638::ExecJS"` probably you have some issues with ExecJS or mini_racer gem, so go through their [installation instructions](https://github.com/rubyjs/mini_racer) 

also check 

https://github.com/shakacode/react_on_rails/blob/master/docs/basics/react-server-rendering.md#how-do-you-do-server-rendering-with-react-on-rails

**Comment by justin808** [comment]
@nathan-kuo can you push your demo repo to github and share with me?

**Comment by nathan-kuo** [comment]
@justin808 of course, here is the [repo](https://github.com/nathan-kuo/react_on_rails_nathan).

**Comment by nathan-kuo** [comment]
@justin808 thank you for looking into this.  

It is working now.

It was missing the ExecJS's gem.  And a little modification to the **Procfile.dev-server** from **bin/webpack-dev-server --inline=false** to **bin/webpack -w**

**Comment by justin808** [comment]
Hi @nathan-kuo Why did you set inline=false?

https://webpack.js.org/configuration/dev-server/#devserverinline

**Comment by dklanac** [comment]
I'm actually getting this precise error. I'm sidestepping Foreman in favor of Docker Compose, but it appears to achieve the same end. Here are my relevant configurations:

`docker-compose.yml`
```
version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: >
      sh -c "rm -f tmp/pids/server.pid &&
      rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/deploy
    ports:
      - "3000:3000"
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpacker
    depends_on:
      - db
  webpacker:
    image: cc_web
    env_file:
      - ".env.docker"
    command: >
      sh -c "rm -rf public/packs/* || true &&
      bundle exec rake react_on_rails:locale &&
      bin/webpack -w"
    volumes:
      - .:/deploy
    ports:
      - "3035:3035"
```

`webpacker.yml`
```
version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: >
      sh -c "rm -f tmp/pids/server.pid &&
      rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/deploy
    ports:
      - "3000:3000"
    depends_on:
      - db
  webpacker:
    image: cc_web
    command: >
      sh -c "rm -rf public/packs/* || true &&
      bundle exec rake react_on_rails:locale &&
      bin/webpack -w"
    volumes:
      - .:/deploy
    ports:
      - "3035:3035"
```
