### ISSUE TITLE
Invalid call to renderToString in Staging

### ISSUE THREAD

**Issue by newfylox** [shakacode/react_on_rails#1357]
react_on_rails: 12.0.4

Hi guys! I work in development mode and everything works fine. But today I tried to deploy my code in staging and I'm having this error :

```text
Invalid call to renderToString. Possibly you have a renderFunction, a function that already
calls renderToString, that takes one parameter. You need to add an extra unused
parameter to identify this function as a renderFunction and not a simple React 
Function Component
```

I can still navigate my website with no other errors, but that's bugging me to see this error at every refresh (F5).

Any idea?

```js
// config/webpack/environment.js
const getEnvironment = (RAILS_ENV) => {
  const { environment } = require("@rails/webpacker");
  const webpack = require("webpack");
  const dotenv = require("dotenv");

  const dotenvFiles = [
    `.env.${RAILS_ENV}.local`,
    ".env.local",
    `.env.${RAILS_ENV}`,
    ".env",
  ];
  dotenvFiles.forEach((dotenvFile) => {
    dotenv.config({ path: dotenvFile, silent: true });
  });

  environment.plugins.prepend(
    "Environment",
    new webpack.EnvironmentPlugin(JSON.parse(JSON.stringify(process.env)))
  );

  return environment;
};

module.exports = getEnvironment;
```

```js
// config/webpack/staging.js
process.env.NODE_ENV = 'production'

const getEnvironment = require('./environment')

module.exports = getEnvironment('staging').toWebpackConfig()
```

```yml
# config/webpacker.yml
...
staging:
  <<: *default

  # Production depends on precompilation of packs prior to booting for performance.
  compile: false

  # Extract and emit a css file
  extract_css: true

  # Cache manifest.json for performance
  cache_manifest: true
```
