### ISSUE TITLE
How do I stop react_on_rails from generating packs?

### ISSUE THREAD

**Issue by brandoncc** [shakacode/react_on_rails#1536]
Hello,

For background, I'm upgrading an app from webpacker 3.5, react-on-rails 11.3, and sprockets 3.7 to shakapacker 6.6, react-on-rails 13.3, and sprockets 4.2.

The approach I took was to delete all remnants of webpacker and react_on_rails, then set them up as a new installation. Overall, this has worked very well for me. I have development and staging working perfectly from what I can tell.

In CI, however, things are completely broken.

##### Extra context

I have this in `spec/support`, and it is being required by `rails_helper` (rspec).

```ruby
RSpec.configure do |config|
  ReactOnRails::TestHelper.configure_rspec_to_compile_assets(config)
end
```

### What I expect to happen

I expect the packs in `app/javascript/packs` to be compiled just as they are in development and staging.

Side note: I discovered automated bundle generation and thought that must be the right way to go, so I also attempted to embrace that fully.

#### When I wasn't trying to use automatic bundle generation (my preferred approach for this upgrade transition)

react-on-rails is generating packs for all of my javascript files, including generating packs from my pack files. I cannot figure out how to stop this behavior.

Here is an error I'm running into:

I have a file named `app/javascript/packs/admin-bundle.js` and also a bunch of files in `app/javascript/components/admin/` and react on rails is generating `generated/admin-bundle.js` with:

```js
ReactOnRails.register({ admin-bundle });
```

Not only is this a syntax error, it is somehow colliding with another pack file that is being generated called `admin`.

```
...
...
Generated Packs: /home/circleci/repo/app/javascript/packs/generated/popupLocationCalculator.js
Generated Packs: /home/circleci/repo/app/javascript/packs/generated/railsUjs.js
Generated Packs: /home/circleci/repo/app/javascript/packs/generated/replaceState.js
Generated Packs: /home/circleci/repo/app/javascript/packs/generated/typestyle.js
Generated Packs: /home/circleci/repo/app/javascript/packs/generated/viewHelpers.js
Generated Packs: /home/circleci/repo/app/javascript/packs/generated/view_helpers.js
Prepended
// import statement added by react_on_rails:generate_packs rake task
import "./server-bundle-generated.js"
to /home/circleci/repo/app/javascript/packs/server-bundle.js.
Generated Server Bundle: /home/circleci/repo/app/javascript/packs/server-bundle-generated.js

...
...

WARNING in DefinePlugin
Conflicting values for 'process.env.NODE_ENV'

1 warning has detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

ERROR in ./app/javascript/packs/server-bundle-generated.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /home/circleci/repo/app/javascript/packs/server-bundle-generated.js: Identifier 'admin' has already been declared. (390:7)

  388 | import useSSRComponent from 'generated/useSSRComponent.js';
  389 | import packs from 'generated/packs.js';
> 390 | import admin-bundle from 'generated/admin-bundle.js';
      |        ^
```

### Things I've tried

Here are some `react_on_rails.rb` initializer configs that I've tried:

```ruby
ReactOnRails.configure do |config|
  # config.build_production_command = nil
  config.build_test_command = "RAILS_ENV=test bin/webpacker"
  config.server_bundle_js_file = "server-bundle.js"
  config.raise_on_prerender_error = Rails.env.development? || Rails.env.staging?
  # config.components_subdirectory = "ror_components"
  config.auto_load_bundle = false
end
```

```ruby
ReactOnRails.configure do |config|
  # config.build_production_command = nil
  config.build_test_command = "NODE_ENV=test RAILS_ENV=test bin/webpacker"
  config.server_bundle_js_file = "server-bundle.js"
  config.raise_on_prerender_error = Rails.env.development? || Rails.env.staging?
  # config.components_subdirectory = "ror_components"
  config.auto_load_bundle = false
end
```

```ruby
ReactOnRails.configure do |config|
  # config.build_production_command = nil
  config.build_test_command = "REACT_ON_RAILS_PRECOMPILE=false  NODE_ENV=test RAILS_ENV=test bin/webpacker"
  config.server_bundle_js_file = "server-bundle.js"
  config.raise_on_prerender_error = Rails.env.development? || Rails.env.staging?
  # config.components_subdirectory = "ror_components"
  config.auto_load_bundle = false
end
```

```ruby
ReactOnRails.configure do |config|
  config.build_production_command = nil
  config.build_test_command = "NODE_ENV=test RAILS_ENV=test bin/webpacker"
  config.server_bundle_js_file = "server-bundle.js"
  config.raise_on_prerender_error = Rails.env.development? || Rails.env.staging?
  # config.components_subdirectory = "ror_components"
  config.auto_load_bundle = false
end
```

```ruby
ReactOnRails.configure do |config|
  config.build_production_command = "RAILS_ENV=production NODE_ENV=production bin/webpacker"
  config.build_test_command = "NODE_ENV=test RAILS_ENV=test bin/webpacker"
  config.server_bundle_js_file = "server-bundle.js"
  config.raise_on_prerender_error = Rails.env.development? || Rails.env.staging?
  # config.components_subdirectory = "ror_components"
  config.auto_load_bundle = false
end
```

```ruby
ReactOnRails.configure do |config|
  # config.build_production_command = nil
  config.build_test_command = "NODE_ENV=test RAILS_ENV=test bin/webpacker"
  config.server_bundle_js_file = "server-bundle.js"
  config.raise_on_prerender_error = Rails.env.development? || Rails.env.staging?
  config.components_subdirectory = "ror_components"
  config.auto_load_bundle = true
end
```

I have also tried various combinations of `compile: true` and `compile: false` for `test` in `webpacker.yml` along with `webpacker_precompile: false` and `webpacker_precompile: true`.

I also added `new webpack.EnvironmentPlugin(['NODE_ENV']),` as a plugin in `config/webpack/commonWebpackConfig.js`.

#### When I was trying to use automatic pack generation

```
ERROR in ./app/javascript/packs/server-bundle-generated.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/brandoncc/dev/the-site/app/javascript/packs/server-bundle-generated.js: Unexpected token, expected "from" (401:13)

  399 | import seoContent from '../src/contexts/seoContent.js';
  400 | import seo_content from '../src/types/seo_content.js';
> 401 | import server-bundle from 'server-bundle.js';
      |              ^
```

**Comment by justin808** [comment]
1. This task should run: https://github.com/shakacode/react_on_rails/blob/master/lib/tasks/generate_packs.rake#L8
2. That is called by https://github.com/shakacode/react_on_rails/blob/master/lib/react_on_rails/configuration.rb#L160
3. Which is called by rake assets:precompile by this line: https://github.com/shakacode/react_on_rails/blob/master/lib/react_on_rails/configuration.rb#L173

Maybe you are not running rake assets:precompile for your CI builds?

**Comment by brandoncc** [comment]
Hi Justin, it does appear that the missing step I needed was to precompile assets in CI before running the tests. I have never had to do this before, so I'm definitely surprised that this resolves the issue.

It seems like running `bin/rails assets:precompile` and letting rspec precompile on demand should output the same files, but that is not the case. For example, when I remove the asset precompilation that seems to fix the problem, I see this in my logs:

```
====> React On Rails: Checking files in /home/circleci/repo/public/packs-**** for outdated/missing bundles based on source_path /home/circleci/repo/app/javascript

Generated Packs: /home/circleci/repo/app/javascript/packs/generated/SideMenuRouter.js
Generated Packs: /home/circleci/repo/app/javascript/packs/generated/SideMenuRoutes.js
Generated Packs: /home/circleci/repo/app/javascript/packs/generated/SideMenuServerRouter.js
Generated Packs: /home/circleci/repo/app/javascript/packs/generated/Styles.js
Generated Packs: /home/circleci/repo/app/javascript/packs/generated/app_routes.js
Generated Packs: /home/circleci/repo/app/javascript/packs/generated/admin.js
```

When I run `bin/rails assets:precompile` as a CI step before running my tests, though, I don ot see any packs generated.

Is there a simple explanation for this difference?

Thank you for your help!

**Comment by brandoncc** [comment]
By the way, my best as a cause for this issue is that it says it is looking for missing bundles "based on source_path /home/circleci/repo/app/javascript", but I think it needs to be looking based on "/home/circleci/repo/app/javascript/packs"...

**Comment by justin808** [comment]
As an alternative to precompiling, you can run https://github.com/shakacode/react_on_rails/blob/master/lib/tasks/generate_packs.rake#L9 manually before you build your bundles.

@ahangarha can you check if the error message is wrong per the above message?

**Comment by brandoncc** [comment]
> As an alternative to precompiling, you can run https://github.com/shakacode/react_on_rails/blob/master/lib/tasks/generate_packs.rake#L9 manually before you build your bundles.
> 
> @ahangarha can you check if the error message is wrong per the above message?

@justin808 respectfully, I think you have my request backward. Why would I want to run `react_on_rails:generate_packs` manually? This is the command that is causing me the problems. This is the command that I do not want to run _under any circumstances_.

**Comment by brandoncc** [comment]
> @brandoncc
> 
> > By the way, my best guess as a cause for this issue is that it says it is looking for missing bundles "based on source_path /home/circleci/repo/app/javascript", but I think it needs to be looking based on "/home/circleci/repo/app/javascript/packs"...
> 
> For this, you need to set `source_entry_path` to `packs`.

@ahangarha sorry, I didn't think about posting my webpacker.yml. `source_entry_path` is already `packs`. It seems that all of the files in `source_path` are being turned into bundles, and the files in `app/javascript/packs` are as well even with out nesting on.

I also tried setting `source_path` to `app/javascript/packs` with `source_entry_path` both empty and `/`. Both of these led to errors.

```yml
# Note: You must restart bin/webpacker-dev-server for changes to take effect

default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/webpacker
  webpack_compile_output: true

  # Additional paths webpack should lookup modules
  # ['app/assets', 'engine/foo/app/assets']
  additional_paths: []

  # Reload manifest.json on all requests so we reload latest compiled packs
  cache_manifest: false

development:
  <<: *default
  # This is false since we're running `bin/webpacker -w` in Procfile.dev-setic
  compile: false

  # Reference: https://webpack.js.org/configuration/dev-server/
  dev_server:
    https: false
    host: localhost
    port: 3035
    # Hot Module Replacement updates modules while the application is running without a full reload
    hmr: true
    client:
      # Should we show a full-screen overlay in the browser when there are compiler errors or warnings?
      overlay: true
      # May also be a string
      # webSocketURL:
      #  hostname: "0.0.0.0"
      #  pathname: "/ws"
      #  port: 8080
    compress: true
    # Note that apps that do not check the host are vulnerable to DNS rebinding attacks
    allowed_hosts: [ 'localhost' ]
    pretty: true
    headers:
      'Access-Control-Allow-Origin': '*'
    static:
      watch:
        ignored: '**/node_modules/**'

test:
  <<: *default
  compile: true

  # Compile test packs to a separate directory
  public_output_path: packs-test

production:
  <<: *default

  # Production depends on precompilation of packs prior to booting for performance.
  compile: false

  # Cache manifest.json for performance
  cache_manifest: true

staging:
  <<: *default

  # Production depends on precompilation of packs prior to booting for performance.
  compile: false

  # Cache manifest.json for performance
  cache_manifest: true
```
