### ISSUE TITLE
Issues deploying to Elastic Beanstalk with Yarn

### ISSUE THREAD

**Issue by chrisjones-tripletri** [shakacode/react_on_rails#766]
I have used React on Rails several times and really appreciate it.  Thanks for all your work.   Historically, it would just deploy to AWS Elastic Beanstalk without issues.   However, with the switch to Yarn, which is not installed on the AWS linux image, it no longer does.

I tried changing the config.npm_build_production_command, but that did not resolve the issue.  In addition, I felt it was better to use the same package manager in dev and production.

After much fiddling around, I found that adding a yarn.config file in the .ebextensions folder resolved the issue:

```
commands:

  01_node_get:
    # run this command from /tmp directory
    cwd: /tmp
    # flag -y for no-interaction installation
    command: 'sudo curl --silent --location https://rpm.nodesource.com/setup_6.x | sudo bash -'

  02_node_install:
    # run this command from /tmp directory
    cwd: /tmp
    command: 'sudo yum -y install nodejs'

  03_yarn_get:
    # run this command from /tmp directory
    cwd: /tmp
    # don't run the command if yarn is already installed (file /usr/bin/yarn exists)
    test: '[ ! -f /usr/bin/yarn ] && echo "yarn not installed"'
    command: 'sudo wget https://dl.yarnpkg.com/rpm/yarn.repo -O /etc/yum.repos.d/yarn.repo'


  04_yarn_install:
    # run this command from /tmp directory
    cwd: /tmp
    test: '[ ! -f /usr/bin/yarn ] && echo "yarn not installed"'
    command: 'sudo yum -y install yarn'
```

I am certain there is some better, more concise way to achieve this, but I not an AWS expert.  This worked for me.

Anyway, I thought it might be worth documenting here, in case other people are trying to deploy a react-on-rails app to Elastic Beanstalk.

Thanks for all your efforts!  React on Rails was the first framework that enabled me to achieve really good results with a javascript/client-side app.
