### ISSUE TITLE
Version 8 beta suggested improvements

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#833]
1. Need to document all values in this file or slim down 
https://github.com/shakacode/react_on_rails/blob/master/lib/generators/react_on_rails/templates/base/base/config/webpack/paths.yml
```yaml
default: &default
  output: public
  assets: webpack
  manifest: manifest.json
  node_modules: client/node_modules
  source: client/app

development:
  <<: *default
  assets: webpack/development

test:
  <<: *default
  assets: webpack/test

production:
  <<: *default
  assets: webpack/production
```
